apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: amf
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
  - name: ngap		 # Next-Generation Application Protocol (between gNodeB - AMF)
    port: 38412
    protocol: SCTP
#   nodePort: 36412
  selector:
    epc-role: amf    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: amf
  namespace: $K8S_NAMESPACE
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "amf"
  selector:
    matchLabels:
      epc-role: amf
  template:
    metadata:
      labels:
        epc-role: amf
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/amf.yaml | envsubst > /etc/open5gs/amf.yaml"]
          volumeMounts:
            - name: amf-configmap-volume
              mountPath: /tmp/
            - name: amf-data-volume
              mountPath: /etc/open5gs/
          env:
            - name: AMF_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: amf
          image: $IMAGE_REPO/open5gs:$CN5T_RELEASE
          imagePullPolicy: Always
          command: ["open5gs-amfd", "-c", "/etc/open5gs/amf.yaml"]
#  command: ["/bin/bash","-c","sleep 3600"]
          volumeMounts:
          - name: amf-data-volume
            mountPath: /etc/open5gs/
      volumes:
        - name: amf-configmap-volume
          configMap:
            name: open5gs-amf-config
        - name: amf-data-volume
          emptyDir: {}

