apiVersion: v1
kind: Service
metadata:
  name: nrf
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: nrf
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
  selector:
    epc-role: nrf    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: nrf
  namespace: $K8S_NAMESPACE
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "nrf"
  selector:
    matchLabels:
      epc-role: nrf
  template:
    metadata:
      labels:
        epc-role: nrf
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/nrf.yaml | envsubst > /etc/open5gs/nrf.yaml"]
          volumeMounts:
            - name: nrf-configmap-volume
              mountPath: /tmp/
            - name: nrf-data-volume
              mountPath: /etc/open5gs/
          env:
            - name: NRF_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: nrf
          image: ghcr.io/mattereppe/open5gs:$CN5T_RELEASE
          imagePullPolicy: Always
          volumeMounts:
            - name: nrf-data-volume
              mountPath: /etc/open5gs/
          command: ["open5gs-nrfd", "-c", "/etc/open5gs/nrf.yaml"]
# command: ["/bin/bash","-c","sleep 3600"]
      volumes:
        - name: nrf-configmap-volume
          configMap:
            name: open5gs-nrf-config
        - name: nrf-data-volume
          emptyDir: {}

