apiVersion: v1
kind: Service
metadata:
  name: smf
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: smf
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
# gtpc, pfcp?
  - name: pfcp
    port: 8805
    protocol: UDP
  - name: gtpu
    port: 2152
    protocol: UDP
  - name: gtpc
    port: 2123
    protocol: UDP
  selector:
    epc-role: smf    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: smf
  namespace: $K8S_NAMESPACE
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "smf"
  selector:
    matchLabels:
      epc-role: smf
  template:
    metadata:
      labels:
        epc-role: smf
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/smf.yaml | envsubst > /etc/open5gs/smf.yaml"]
          volumeMounts:
            - name: smf-configmap-volume
              mountPath: /tmp/
            - name: smf-data-volume
              mountPath: /etc/open5gs/
          env:
            - name: SMF_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: smf
          image: ghcr.io/mattereppe/open5gs:$CN5T_RELEASE
          imagePullPolicy: Always
          command: ["open5gs-smfd", "-c", "/etc/open5gs/smf.yaml"]
          volumeMounts:
          - name: smf-data-volume
            mountPath: /etc/open5gs
#          - name: smf-fd-configmap-volume
#            mountPath: /etc/freeDiameter/smf.conf
#            subPath: smf.conf
      volumes:
        - name: smf-configmap-volume
          configMap:
            name: open5gs-smf-config
        - name: smf-data-volume
          emptyDir: {}
#        - name: smf-fd-configmap-volume
#          configMap:
#            name: freediameter-smf-config
