apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: udm
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
  selector:
    epc-role: udm    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: udm
  namespace: $K8S_NAMESPACE
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "udm"
  selector:
    matchLabels:
      epc-role: udm
  template:
    metadata:
      labels:
        epc-role: udm
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/udm.yaml | envsubst > /etc/open5gs/udm.yaml"]
          volumeMounts:
            - name: udm-configmap-volume
              mountPath: /tmp/
            - name: udm-data-volume
              mountPath: /etc/open5gs/
          env:
            - name: UDM_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: udm
          image: $IMAGE_REPO/open5gs:$CN5T_RELEASE
          imagePullPolicy: Always
          command: ["open5gs-udmd", "-c", "/etc/open5gs/udm.yaml"]
          volumeMounts:
          - name: udm-data-volume
            mountPath: /etc/open5gs
      volumes:
        - name: udm-configmap-volume
          configMap:
            name: open5gs-udm-config
        - name: udm-data-volume
          emptyDir: {}

