apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: curl-client
  labels: 
    ddos: goldeneye
  namespace: $K8S_NAMESPACE
spec:
  replicas: $CURL_REPLICAS
  selector:
    matchLabels:
      ddos: curlclient
  template:
    metadata:
      labels:
        ddos: curlclient
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c"]
          args:
          - 'export UEID=`echo $PODNAME |  sed -E "s/.*-([[:digit:]]{1,2})/\1/"`;
            UEID=$(( UEID + 1 ));
            UEID=`printf "%010d" ${UEID}`;
            cat /tmp/ue.yaml | envsubst > /etc/ueransim/ue.yaml;'
          volumeMounts:
          - name: ue-configmap-volume
            mountPath: /tmp/
          - name: ue-data-volume
            mountPath: /etc/ueransim
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      containers:
        - name: curl
          image: $IMAGE_REPO/curl:$CN5T_RELEASE
          imagePullPolicy: Always
          volumeMounts:
          - name: curl-configmap-volume
            mountPath: /etc/curl/
          securityContext:
            runAsUser: 0
          command: ["/bin/bash","-c"]
          args:
          - 'while true; do 
               while read url; do
                 echo $url; 
                 curl -b cookie -c cookie -o /dev/null --connect-timeout $CURL_TIMEOUT -s -S  -L $url; 
                 sleep $CURL_DELAY; 
               done < <(sort -R /etc/curl/urls.txt);
             done;'
        - name: ue
          image: $IMAGE_REPO/ueransim:$CN5T_RELEASE
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: Always
          command: ["nr-ue", "-c", "/etc/ueransim/ue.yaml"]
          volumeMounts:
          - name: ue-data-volume
            mountPath: /etc/ueransim/
          - name: dev-net-tun
            mountPath: /dev/net/tun
          livenessProbe:
            exec:
              command:
              - ip
              - a 
              - show
              - dev
              - uesimtun0
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always
      volumes:
        - name: ue-configmap-volume
          configMap:
            name: ueransim-ue-config
        - name: ue-data-volume
          emptyDir: {}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: curl-configmap-volume
          configMap:
            name: curl-client-config
      restartPolicy: Always
