apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goldeneye
  labels: 
    ddos: goldeneye
  namespace: $K8S_NAMESPACE
spec:
  replicas: $DDOS_REPLICAS
  selector:
    matchLabels:
      ddos: goldeneye
  template:
    metadata:
      labels:
        ddos: goldeneye
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c"]
          args:
          - 'export UEID=`echo $PODNAME |  sed -E "s/.*-([[:digit:]]{1,2})/\1/"`;
            UEID=$(( UEID + 1000000001 ));
            cat /tmp/ue.yaml | envsubst > /etc/ueransim/ue.yaml;'
          volumeMounts:
          - name: ue-configmap-volume
            mountPath: /tmp/
          - name: ue-data-volume
            mountPath: /etc/ueransim
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      containers:
        - name: goldeneye
          image: ghcr.io/mattereppe/goldeneye:$CN5T_RELEASE
          imagePullPolicy: Always
          env:
            - name: WORKERS
              value: "$GOLDENEYE_WORKERS"
            - name: SOCKETS
              value: "$GOLDENEYE_SOCKETS"
            - name: METHOD
              value: "$GOLDENEYE_METHOD"
            - name: URL
              value: "$GOLDENEYE_URL"
        - name: ue
          image: ghcr.io/mattereppe/ueransim:$CN5T_RELEASE
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: Always
          command: ["nr-ue", "-c", "/etc/ueransim/ue.yaml"]
          volumeMounts:
          - name: ue-data-volume
            mountPath: /etc/ueransim/
          - name: dev-net-tun
            mountPath: /dev/net/tun
          livenessProbe:
            exec:
              command:
              - ip
              - a 
              - show
              - dev
              - uesimtun0
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: ue-configmap-volume
          configMap:
            name: ueransim-ue-config
        - name: ue-data-volume
          emptyDir: {}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
      restartPolicy: Always
