apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: $K8S_NAMESPACE
  labels:
    role: webserver
spec:
  selector:
    role: webserver
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP    
    targetPort: 80
    nodePort: 30088
  - name: openc2  # OpenC2 MIRANDA connector
    port: 8080
    protocol: TCP
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: http
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  serviceName: "http"
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            {
             	 "name": "datanetwork1",
             	 "ips": [ "$NETADDR_VICTIM" ]
            }
        ]'
      labels:
        role: webserver
    spec:
      initContainers:
        - name: routeadd
          image: $IMAGE_REPO/open5gs:$CN5T_RELEASE
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          command: ["/bin/sh", "-c"]
          args:
            - ip route add 10.45.0.0/16 via $ADDR_UEGW;
        - name: replace-env-variables-connector
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/connector.yaml | envsubst > /config/connector.yaml"]
          volumeMounts:
            - name: connector-configmap-volume
              mountPath: /tmp/
            - name: connector-config-volume
              mountPath: /config
          env:
            - name: CONNECTOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: http
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          command: ['/usr/bin/python3', '/usr/local/bin/gunicorn']
          args:
            - -b 0.0.0.0:80
            - httpbin:app
            - -k gevent
            - --capture-output
            - --access-logfile=/var/log/http_access.log
            - --error-logfile=/var/log/http_error.log
        - name: miranda-connector
          image: $IMAGE_REPO/connector:$CONNECTOR_RELEASE
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: Always
          command: ["python3", "connector.py", "-c", "/config/connector.yaml"]
          volumeMounts:
          - name: connector-data-volume
            mountPath: /data
          - name: connector-config-volume
            mountPath: /config
          - name: fclm-filebeat-volume
            mountPath: /actuators-config/fclm-filebeat.yaml
            subPath: fclm-filebeat.yaml
      volumes:
        - name: connector-configmap-volume
          configMap:
            name: connector-config
        - name: connector-config-volume
          emptyDir: {}
        - name: connector-data-volume
          emptyDir: {}
        - name: fclm-filebeat-volume
          configMap:
            name: fclm-config-filebeat

