apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: datanetwork1
  namespace: $K8S_NAMESPACE
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "$NETIFACE1",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'

