apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret-open5gs
  namespace: $K8S_NAMESPACE
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWF0dGVyZXBwZSIsInBhc3N3b3JkIjoiZ2hwX2dzNjZLVjRqaGtSc3lzdFE0S21Xa2lVWHk2b1dRNzJ2blRPWCIsImVtYWlsIjoibWF0dGVyZXBwZUBnbWFpbC5jb20iLCJhdXRoIjoiYldGMGRHVnlaWEJ3WlRwbmFIQmZaM00yTmt0V05HcG9hMUp6ZVhOMFVUUkxiVmRyYVZWWWVUWnZWMUUzTW5adVZFOVkifX19
