apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-config
  namespace: $K8S_NAMESPACE
  labels:
    ran-role: gnb
data:
  gnb.yaml: |
    mcc: $OPEN5GS_MCC
    mnc: $OPEN5GS_MNC
    
    nci: 0x000000010
    idLength: 32
    tac: $OPEN5GS_TAC
    
    linkIp: $GNB_POD_IP
    ngapIp: $GNB_POD_IP
    gtpIp: $GNB_POD_IP
    
    amfConfigs:
      - address: amf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
        port: 38412
    
    slices:
      - sst: $OPEN5GS_SST
    
    ignoreStreamIds: true
