apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: open5gs
  labels:
    role: webui
spec:
  type: NodePort
  ports:
  - name: mgmt      # Management port
    port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP    
  selector:
    role: webui    
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webui
  namespace: open5gs
  labels:
    segment: core
    plane: mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      role: webui
  template:
    metadata:
      labels:
        role: webui
    spec:
      containers:
        - name: webui
          image: ghcr.io/mattereppe/webui:main
          imagePullPolicy: Always
          command: ["npm","run","start"]
          envFrom:
            - configMapRef:
                name: open5gs-webui-config 
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs

