apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-mongodb
  namespace: open5gs
spec:
  storageClassName: static-pv
  capacity:
    storage: 100Mi
  accessModes: 
    - ReadWriteMany
  nfs:
    path: /srv/mongodb
    server: 172.21.100.31
