apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: open5gs
  labels:
    epc-role: amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log
    amf:
        sbi:
          - addr: $AMF_POD_IP
            port: 7777
        ngap:
          - addr: $AMF_POD_IP
        guami:
          - plmn_id:
              mcc: 001
              mnc: 01
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: 001
              mnc: 01
            tac: 1
        plmn_support:
          - plmn_id:
              mcc: 001
              mnc: 01
            s_nssai:
              - sst: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf0
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
