apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: open5gs
  labels:
    epc-role: ausf
data:
  ausf.yaml: |
    logger:
        file: /var/log/open5gs/ausf.log
    ausf:
        sbi:
          - addr: $AUSF_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
