apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  namespace: open5gs
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    logger:
        file: /var/log/open5gs/bsf.log

    db_uri: mongodb://localhost/open5gs
    
    bsf:
        sbi:
          - addr: 0.0.0.0
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
