apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-config
  namespace: open5gs
  labels:
    ran-role: gnb
data:
  gnb.yaml: |
    mcc: 001
    mnc: 01
    
    nci: 0x000000010
    idLength: 32
    tac: 1
    
    linkIp: $GNB_POD_IP
    ngapIp: $GNB_POD_IP
    gtpIp: $GNB_POD_IP
    
    amfConfigs:
      - address: 192.168.0.207
        port: 38412
    
    slices:
      - sst: 1
    
    ignoreStreamIds: true
