apiVersion: v1
kind: Service
metadata:
  name: gnb
  namespace: open5gs
  labels:
    ran-role: gnodeb
spec:
  ports:
  - name: rls      # Radio Link Simulator (UERANSIM-specific)
    port: 4997
    protocol: UDP    
  selector:
    ran-role: gnodeb    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: gnb
  namespace: open5gs
  labels:
    segment: ran
spec:
  replicas: 1
  serviceName: "gnb-svc"
  selector:
    matchLabels:
      ran-role: gnodeb
  template:
    metadata:
      labels:
        ran-role: gnodeb
    spec:
      containers:
        - name: gnb
          image: ghcr.io/mattereppe/ueransim:main
          imagePullPolicy: Always
#command: ["nr-gnb", "-c", "/etc/ueransim/open5gs-gnb.yaml"]
          command: ["/bin/bash", "-c", "sleep 3600"]
          volumeMounts:
          - name: gnb-configmap-volume
            mountPath: /etc/ueransim
#            subPath: "amf.yaml"            # Not really necessary; just consider that all existing files are "masked" by a single mme.yaml file
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: gnb-configmap-volume
          configMap:
            name: open5gs-gnb-config

