#apiVersion: v1
#kind: Service
#metadata:
#  name: amf
#  namespace: open5gs
#  labels:
#    epc-role: amf
#spec:
#  ports:
#  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
#    port: 7777
#    protocol: TCP    
#  - name: ngap		 # Next-Generation Application Protocol (between gNodeB - AMF)
#    port: 38412
#    protocol: SCTP
##   nodePort: 36412
#  selector:
#    epc-role: amf    
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pv-mongodb
  namespace: open5gs
spec:
  storageClassName: static-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mongodb
  namespace: open5gs
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "mongodb-svc"
  selector:
    matchLabels:
      epc-role: mongodb
  template:
    metadata:
      labels:
        epc-role: mongodb
    spec:
      volumes:
        - name: pv-mongodb
          persistentVolumeClaim:
            claimName: static-pv-mongodb
      containers:
        - name: mongodb
          image: ghcr.io/mattereppe/open5gs:main
          imagePullPolicy: Always
          command: ["sh","-c","sleep 600"]
          volumeMounts:
          - name: pv-mongodb
            mountPath: /srv
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs

