apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: open5gs
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
        file: /var/log/open5gs/nrf.log

    db_uri: mongodb://localhost/open5gs
    
    nrf:
        sbi:
          addr:
            - 0.0.0.0
          port: 7777
