apiVersion: v1
kind: Service
metadata:
  name: nrf
  namespace: open5gs
  labels:
    epc-role: nrf
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
  selector:
    epc-role: nrf    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: nrf
  namespace: open5gs
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "nrf"
  selector:
    matchLabels:
      epc-role: nrf
  template:
    metadata:
      labels:
        epc-role: nrf
    spec:
      containers:
        - name: nrf
          image: ghcr.io/mattereppe/open5gs:main
          imagePullPolicy: Always
#command: ["open5gs-nrfd", "-c", "/etc/open5gs/nrf.yaml"]
          command: ["/bin/bash","-c","sleep 3600"]
          volumeMounts:
          - name: nrf-configmap-volume
            mountPath: /etc/open5gs
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: nrf-configmap-volume
          configMap:
            name: open5gs-nrf-config

