apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
  labels:
    epc-role: nssf
data:
  nssf.yaml: |
    logger:
        file: /var/log/open5gs/nssf.log
    nssf:
        sbi:
          - addr: $NSSF_POD_IP
            port: 7777
        nsi:
          - addr: ::1
            port: 7777
            s_nssai:
              sst: 1
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
