apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: open5gs
  labels:
    epc-role: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log

    db_uri: mongodb://mongodb.open5gs.svc.k8s.tnt-lab.local/open5gs
    
    pcf:
        sbi:
          - addr: $PCF_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
