apiVersion: v1
kind: Service
metadata:
  name: scp
  namespace: open5gs
  labels:
    epc-role: scp
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
  selector:
    epc-role: scp
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: scp
  namespace: open5gs
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "scp"
  selector:
    matchLabels:
      epc-role: scp
  template:
    metadata:
      labels:
        epc-role: scp
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/scp.yaml | envsubst > /etc/open5gs/scp.yaml"]
          volumeMounts:
            - name: scp-configmap-volume
              mountPath: /tmp/
            - name: scp-data-volume
              mountPath: /etc/open5gs/
          env:
            - name: SCP_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: scp
          image: ghcr.io/mattereppe/open5gs:main
          imagePullPolicy: Always
          command: ["open5gs-scpd", "-c", "/etc/open5gs/scp.yaml"]
          volumeMounts:
          - name: scp-data-volume
            mountPath: /etc/open5gs
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: scp-configmap-volume
          configMap:
            name: open5gs-scp-config
        - name: scp-data-volume
          emptyDir: {}

