apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    smf:
        sbi:
          - addr: 0.0.0.0
            port: 7777
        pfcp:
          - addr: 0.0.0.0
        gtpc:
          - addr: 0.0.0.0
        gtpu:
          - addr: 0.0.0.0
        subnet:
          - addr: 10.45.0.1/16
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400
        freeDiameter: /etc/freeDiameter/smf.conf
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
    
    upf:
        pfcp:
          - name: upf.open5gs.svc.k8s.tnt-lab.local
            apn: internet
