apiVersion: v1
kind: Service
metadata:
  name: smf
  namespace: open5gs
  labels:
    epc-role: smf
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
# gtpc, pfcp?
  - name: pfcp
    port: 8805
    protocol: UDP
  - name: gtpu
    port: 2152
    protocol: UDP
  - name: gtpc
    port: 2123
    protocol: UDP
  selector:
    epc-role: smf    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: smf
  namespace: open5gs
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "smf-svc"
  selector:
    matchLabels:
      epc-role: smf
  template:
    metadata:
      labels:
        epc-role: smf
    spec:
      containers:
        - name: smf
          image: ghcr.io/mattereppe/open5gs:main
          imagePullPolicy: Always
          command: ["open5gs-smfd", "-d","-c", "/etc/open5gs/smf.yaml"]
          volumeMounts:
          - name: smf-configmap-volume
            mountPath: /etc/open5gs
#            subPath: "amf.yaml"            # Not really necessary; just consider that all existing files are "masked" by a single mme.yaml file
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: smf-configmap-volume
          configMap:
            name: open5gs-smf-config

