apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mongodb
  namespace: open5gs
  labels:
    segment: core
    plane: control
spec:
#terminationGracePeriodSeconds: 10
  replicas: 1
  serviceName: "mongodb-svc"
  selector:
    matchLabels:
      epc-role: mongodb
  template:
    metadata:
      labels:
        epc-role: mongodb
    spec:
      volumes:
        - name: mongodb-configmap-volume
          configMap:
            name: open5gs-mongodb-config
      containers:
        - name: mongodb
          image: ghcr.io/mattereppe/open5gs:main
          imagePullPolicy: Always
          command: ['/bin/sh','-c','sleep 300']
#            - mongod
#            - "--config"
#            - "/etc/mongod.conf"
##            - "--replSet"
#            - rs0
#            - "--smallfiles"
#            - "--noprealloc"
          volumeMounts:
          - name: mongodb-configmap-volume
            mountPath: /etc/mongodb.conf
            subPath: mongod.conf
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs

