apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: open5gs
  labels:
    epc-role: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log

    udm:
        sbi:
          - addr: $UDM_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
