apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: open5gs
  labels:
    epc-role: udm
spec:
  ports:
  - name: sbi      # Service Based Interface (web interface "bus" in the control plane)
    port: 7777
    protocol: TCP    
  selector:
    epc-role: udm    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: udm
  namespace: open5gs
  labels:
    segment: core
    plane: control
spec:
  replicas: 1
  serviceName: "udm-svc"
  selector:
    matchLabels:
      epc-role: udm
  template:
    metadata:
      labels:
        epc-role: udm
    spec:
      containers:
        - name: udm
          image: ghcr.io/mattereppe/open5gs:main
          imagePullPolicy: Always
          command: ["open5gs-udmd", "-c", "/etc/open5gs/udm.yaml"]
          volumeMounts:
          - name: udm-configmap-volume
            mountPath: /etc/open5gs
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: udm-configmap-volume
          configMap:
            name: open5gs-udm-config

