apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: open5gs
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    logger:
        file: /var/log/open5gs/udr.log

    db_uri: mongodb://mongodb.open5gs.svc.k8s.tnt-lab.local/open5gs
    
    logger:
        file: /var/log/open5gs/udr.log
    udr:
        sbi:
          - addr: 0.0.0.0
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
