apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-ue-config
  namespace: open5gs
  labels:
    ran-role: ue
data:
  ue.yaml: |
    supi: 'imsi-001010000000001'
    mcc: '001'
    mnc: '01'
    
    key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
    op: 'E8ED289DEBA952E4283B54E88E6183CA'
    opType: 'OPc'
    amf: '8000'
    imei: '356938035643803'
    imeiSv: '4370816125816151'
    
    gnbSearchList:
      - gnb.open5gs.svc.k8s.tnt-lab.local
    
    sessions:
      - type: 'IPv4'
        apn: 'internet'
        slice:
          sst: 1
          sd: 1
        emergency: false
    
    configured-nssai:
      - sst: 1
        sd: 1
    
    default-nssai:
      - sst: 1
        sd: 1
    
    uacAic:
      mps: false
      mcs: false
    
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
        
    integrity:
      IA1: true
      IA2: true
      IA3: true
    
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
