# Service is not necessary, until there is no way to attach an external pod with a traffic generator
#apiVersion: v1
#kind: Service
#metadata:
#  name: gnb
#  namespace: open5gs
#  labels:
#    ran-role: gnodeb
#spec:
#  ports:
#  - name: rls      # Radio Link Simulator (UERANSIM-specific)
#    port: 4997
#    protocol: UDP    
#  selector:
#    ran-role: gnodeb    
#---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ue
  namespace: open5gs
  labels:
    segment: ran
spec:
  replicas: 1
  selector:
    matchLabels:
      ran-role: ue
  template:
    metadata:
      labels:
        ran-role: ue
    spec:
      containers:
        - name: ue
          image: ghcr.io/mattereppe/ueransim:main
          imagePullPolicy: Always
          command: ["nr-ue", "-c", "/etc/ueransim/ue.yaml"]
          volumeMounts:
          - name: ue-configmap-volume
            mountPath: /etc/ueransim/
      imagePullSecrets: 						  # This to be removed once the image is public
        - name: k8s-secret-open5gs
      volumes:
        - name: ue-configmap-volume
          configMap:
            name: ueransim-ue-config

