apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  namespace: open5gs
  labels:
    epc-role: upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

    upf:
        pfcp:
          - addr: 0.0.0.0
        gtpu:
          - addr: 0.0.0.0
        subnet:
          - addr: 10.45.0.1/16
          - addr: 2001:230:cafe::1/48
