apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-webui-config
  namespace: open5gs
  labels:
    role: webui
data:
  DB_URI: mongodb://mongodb.open5gs.svc.k8s.tnt-lab.local/open5gs
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
  NODE_ENV: production
  SECRET_KEY: "change-me"
