apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: bsf
data:
  bsf.yaml: |
    logger:
        file: /var/log/open5gs/bsf.log

    db_uri: mongodb://mongodb.$K8S_NAMESPACE.svc.$K8S_DOMAIN/open5gs
    
    bsf:
        sbi:
          - addr: $BSF_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
