apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: nssf
data:
  nssf.yaml: |
    logger:
        file: /var/log/open5gs/nssf.log
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
    nssf:
        sbi:
          - addr: $NSSF_POD_IP
            port: 7777
        nsi:
          - addr: nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
            s_nssai:
              sst: 1

    nrf:
        sbi:
          - addr:
              - nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
