apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log

    db_uri: mongodb://mongodb.$K8S_NAMESPACE.svc.$K8S_DOMAIN/open5gs
    
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true

    pcf:
        sbi:
          - addr: $PCF_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
