apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-scp-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: scp
data:
  scp.yaml: |
    logger:
        file: /var/log/open5gs/scp.log

    db_uri: mongodb://mongodb.$K8S_NAMESPACE.svc.$K8S_DOMAIN/open5gs
    
    scp:
        sbi:
          - addr: $SCP_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
