apiVersion: v1
kind: ConfigMap
metadata:
  name: freediameter-smf-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-mode: smf
data:
 smf.conf: |
  Identity = "smf.localdomain";
  Realm = "$K8S_DOMAIN";
  TLS_Cred = "/etc/freeDiameter/smf.cert.pem", "/etc/freeDiameter/smf.key.pem";
  TLS_CA = "/etc/freeDiameter/cacert.pem";

  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx" : "0x8888";
  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx";
  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx";
  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx";
  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx";
  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx";
  LoadExtension = "/usr/src/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx";

# There is no pcrf running in my deployment!
# ConnectPeer = "pcrf.localdomain" { ConnectTo = "pcrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN"; No_TLS; No_SCTP; };
