apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true

    udm:
        sbi:
          - addr: $UDM_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
