apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: $K8S_NAMESPACE
  labels:
    epc-role: udr
data:
  udr.yaml: |
    logger:
        file: /var/log/open5gs/udr.log

    db_uri: mongodb://mongodb.$K8S_NAMESPACE.svc.$K8S_DOMAIN/open5gs
    
    logger:
        file: /var/log/open5gs/udr.log

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true

    udr:
        sbi:
          - addr: $UDR_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.$K8S_NAMESPACE.svc.$K8S_DOMAIN
            port: 7777
