apiVersion: v1
kind: Service
metadata:
  name: gnb
  namespace: $K8S_NAMESPACE
  labels:
    ran-role: gnodeb
spec:
  ports:
  - name: rls      # Radio Link Simulator (UERANSIM-specific)
    port: 4997
    protocol: UDP    
  selector:
    ran-role: gnodeb    
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: gnb
  namespace: $K8S_NAMESPACE
  labels:
    segment: ran
spec:
  replicas: 1
  serviceName: "gnb"
  selector:
    matchLabels:
      ran-role: gnodeb
  template:
    metadata:
      labels:
        ran-role: gnodeb
    spec:
      initContainers:
        - name: replace-env-variables
          image: bhgedigital/envsubst
          command: ["/bin/sh","-c","cat /tmp/gnb.yaml | envsubst > /etc/ueransim/gnb.yaml"]
          volumeMounts:
          - name: gnb-configmap-volume
            mountPath: /tmp/
          - name: gnb-data-volume
            mountPath: /etc/ueransim
          env:
            - name: GNB_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      containers:
        - name: gnb
          image: ghcr.io/mattereppe/ueransim:$CN5T_RELEASE
          imagePullPolicy: Always
          command: ["nr-gnb", "-c", "/etc/ueransim/gnb.yaml"]
# command: ["/bin/bash","-c","sleep 3660"]
          volumeMounts:
          - name: gnb-data-volume
            mountPath: /etc/ueransim
# TODO: replace with better script that takes into account a different name for gnb
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - |-
                amflist=`nr-cli UERANSIM-gnb-1-1-1 --exec amf-list`;
                 test -n "$amflist" || exit 1;
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: gnb-configmap-volume
          configMap:
            name: ueransim-gnb-config
        - name: gnb-data-volume
          emptyDir: {}

