apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-mongodb
spec:
  storageClassName: static-pv
  capacity:
    storage: 100Mi
  accessModes: 
    - ReadWriteMany
  nfs:
    path: /srv/mongodb
    server: 192.168.0.200
