apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: open5gs
  labels:
    epc-role: nrf
data:
  nrf.yaml: |
    logger:
        file: /var/log/open5gs/nrf.log

    db_uri: mongodb://mongodb.open5gs.svc.k8s.tnt-lab.local/open5gs
    
    nrf:
        sbi:
          addr:
            - $NRF_POD_IP
          port: 7777
