apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-scp-config
  namespace: open5gs
  labels:
    epc-role: scp
data:
  scp.yaml: |
    logger:
        file: /var/log/open5gs/scp.log

    db_uri: mongodb://mongodb.open5gs.svc.k8s.tnt-lab.local/open5gs
    
    scp:
        sbi:
          - addr: $SCP_POD_IP
            port: 7777
    
    nrf:
        sbi:
          - addr:
              - nrf.open5gs.svc.k8s.tnt-lab.local
            port: 7777
